# Generated by Django 6.0.3 on 2026-04-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='execution',
            name='nombre1',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
